package com.dtec.helloatu.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CRIME".
 */
public class Crime {

    private Long id;
    private int crimPosition;
    /** Not-null value. */
    private String crimCategory;
    /** Not-null value. */
    private String crimeInfo;
    /** Not-null value. */
    private String informerName;
    /** Not-null value. */
    private String informerPhone;
    /** Not-null value. */
    private String informerAddress;
    /** Not-null value. */
    private String informerEmail;
    /** Not-null value. */
    private String infoDocument;
    /** Not-null value. */
    private String infoPicture;
    /** Not-null value. */
    private String infoVideo;
    /** Not-null value. */
    private String infoAudio;
    /** Not-null value. */
    private String occurrence;
    /** Not-null value. */
    private String occurrenceInformer;
    /** Not-null value. */
    private String division;
    /** Not-null value. */
    private String divisionInformer;
    /** Not-null value. */
    private String district;
    /** Not-null value. */
    private String districtInformer;
    /** Not-null value. */
    private java.util.Date createdAt;

    public Crime() {
    }

    public Crime(Long id) {
        this.id = id;
    }

    public Crime(Long id, int crimPosition, String crimCategory, String crimeInfo, String informerName, String informerPhone, String informerAddress, String informerEmail, String infoDocument, String infoPicture, String infoVideo, String infoAudio, String occurrence, String occurrenceInformer, String division, String divisionInformer, String district, String districtInformer, java.util.Date createdAt) {
        this.id = id;
        this.crimPosition = crimPosition;
        this.crimCategory = crimCategory;
        this.crimeInfo = crimeInfo;
        this.informerName = informerName;
        this.informerPhone = informerPhone;
        this.informerAddress = informerAddress;
        this.informerEmail = informerEmail;
        this.infoDocument = infoDocument;
        this.infoPicture = infoPicture;
        this.infoVideo = infoVideo;
        this.infoAudio = infoAudio;
        this.occurrence = occurrence;
        this.occurrenceInformer = occurrenceInformer;
        this.division = division;
        this.divisionInformer = divisionInformer;
        this.district = district;
        this.districtInformer = districtInformer;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCrimPosition() {
        return crimPosition;
    }

    public void setCrimPosition(int crimPosition) {
        this.crimPosition = crimPosition;
    }

    /** Not-null value. */
    public String getCrimCategory() {
        return crimCategory;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCrimCategory(String crimCategory) {
        this.crimCategory = crimCategory;
    }

    /** Not-null value. */
    public String getCrimeInfo() {
        return crimeInfo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCrimeInfo(String crimeInfo) {
        this.crimeInfo = crimeInfo;
    }

    /** Not-null value. */
    public String getInformerName() {
        return informerName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInformerName(String informerName) {
        this.informerName = informerName;
    }

    /** Not-null value. */
    public String getInformerPhone() {
        return informerPhone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInformerPhone(String informerPhone) {
        this.informerPhone = informerPhone;
    }

    /** Not-null value. */
    public String getInformerAddress() {
        return informerAddress;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInformerAddress(String informerAddress) {
        this.informerAddress = informerAddress;
    }

    /** Not-null value. */
    public String getInformerEmail() {
        return informerEmail;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInformerEmail(String informerEmail) {
        this.informerEmail = informerEmail;
    }

    /** Not-null value. */
    public String getInfoDocument() {
        return infoDocument;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInfoDocument(String infoDocument) {
        this.infoDocument = infoDocument;
    }

    /** Not-null value. */
    public String getInfoPicture() {
        return infoPicture;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInfoPicture(String infoPicture) {
        this.infoPicture = infoPicture;
    }

    /** Not-null value. */
    public String getInfoVideo() {
        return infoVideo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInfoVideo(String infoVideo) {
        this.infoVideo = infoVideo;
    }

    /** Not-null value. */
    public String getInfoAudio() {
        return infoAudio;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInfoAudio(String infoAudio) {
        this.infoAudio = infoAudio;
    }

    /** Not-null value. */
    public String getOccurrence() {
        return occurrence;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOccurrence(String occurrence) {
        this.occurrence = occurrence;
    }

    /** Not-null value. */
    public String getOccurrenceInformer() {
        return occurrenceInformer;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOccurrenceInformer(String occurrenceInformer) {
        this.occurrenceInformer = occurrenceInformer;
    }

    /** Not-null value. */
    public String getDivision() {
        return division;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivision(String division) {
        this.division = division;
    }

    /** Not-null value. */
    public String getDivisionInformer() {
        return divisionInformer;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionInformer(String divisionInformer) {
        this.divisionInformer = divisionInformer;
    }

    /** Not-null value. */
    public String getDistrict() {
        return district;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDistrict(String district) {
        this.district = district;
    }

    /** Not-null value. */
    public String getDistrictInformer() {
        return districtInformer;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDistrictInformer(String districtInformer) {
        this.districtInformer = districtInformer;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

}
