package com.dtec.helloatu.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.dtec.helloatu.dao.Crime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CRIME".
*/
public class CrimeDao extends AbstractDao<Crime, Long> {

    public static final String TABLENAME = "CRIME";

    /**
     * Properties of entity Crime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CrimPosition = new Property(1, int.class, "crimPosition", false, "CRIM_POSITION");
        public final static Property CrimCategory = new Property(2, String.class, "crimCategory", false, "CRIM_CATEGORY");
        public final static Property CrimeInfo = new Property(3, String.class, "crimeInfo", false, "CRIME_INFO");
        public final static Property InformerName = new Property(4, String.class, "informerName", false, "INFORMER_NAME");
        public final static Property InformerPhone = new Property(5, String.class, "informerPhone", false, "INFORMER_PHONE");
        public final static Property InformerAddress = new Property(6, String.class, "informerAddress", false, "INFORMER_ADDRESS");
        public final static Property InfoDocument = new Property(7, String.class, "infoDocument", false, "INFO_DOCUMENT");
        public final static Property InfoPicture = new Property(8, String.class, "infoPicture", false, "INFO_PICTURE");
        public final static Property InfoVideo = new Property(9, String.class, "infoVideo", false, "INFO_VIDEO");
        public final static Property InfoAudio = new Property(10, String.class, "infoAudio", false, "INFO_AUDIO");
        public final static Property Occurrence = new Property(11, String.class, "occurrence", false, "OCCURRENCE");
        public final static Property OccurrenceInformer = new Property(12, String.class, "occurrenceInformer", false, "OCCURRENCE_INFORMER");
        public final static Property Division = new Property(13, String.class, "division", false, "DIVISION");
        public final static Property DivisionInformer = new Property(14, String.class, "divisionInformer", false, "DIVISION_INFORMER");
        public final static Property District = new Property(15, String.class, "district", false, "DISTRICT");
        public final static Property DistrictInformer = new Property(16, String.class, "districtInformer", false, "DISTRICT_INFORMER");
        public final static Property CreatedAt = new Property(17, java.util.Date.class, "createdAt", false, "CREATED_AT");
    };


    public CrimeDao(DaoConfig config) {
        super(config);
    }
    
    public CrimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CRIME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CRIM_POSITION\" INTEGER NOT NULL ," + // 1: crimPosition
                "\"CRIM_CATEGORY\" TEXT NOT NULL ," + // 2: crimCategory
                "\"CRIME_INFO\" TEXT NOT NULL ," + // 3: crimeInfo
                "\"INFORMER_NAME\" TEXT NOT NULL ," + // 4: informerName
                "\"INFORMER_PHONE\" TEXT NOT NULL ," + // 5: informerPhone
                "\"INFORMER_ADDRESS\" TEXT NOT NULL ," + // 6: informerAddress
                "\"INFO_DOCUMENT\" TEXT NOT NULL ," + // 7: infoDocument
                "\"INFO_PICTURE\" TEXT NOT NULL ," + // 8: infoPicture
                "\"INFO_VIDEO\" TEXT NOT NULL ," + // 9: infoVideo
                "\"INFO_AUDIO\" TEXT NOT NULL ," + // 10: infoAudio
                "\"OCCURRENCE\" TEXT NOT NULL ," + // 11: occurrence
                "\"OCCURRENCE_INFORMER\" TEXT NOT NULL ," + // 12: occurrenceInformer
                "\"DIVISION\" TEXT NOT NULL ," + // 13: division
                "\"DIVISION_INFORMER\" TEXT NOT NULL ," + // 14: divisionInformer
                "\"DISTRICT\" TEXT NOT NULL ," + // 15: district
                "\"DISTRICT_INFORMER\" TEXT NOT NULL ," + // 16: districtInformer
                "\"CREATED_AT\" INTEGER NOT NULL );"); // 17: createdAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CRIME\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Crime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCrimPosition());
        stmt.bindString(3, entity.getCrimCategory());
        stmt.bindString(4, entity.getCrimeInfo());
        stmt.bindString(5, entity.getInformerName());
        stmt.bindString(6, entity.getInformerPhone());
        stmt.bindString(7, entity.getInformerAddress());
        stmt.bindString(8, entity.getInfoDocument());
        stmt.bindString(9, entity.getInfoPicture());
        stmt.bindString(10, entity.getInfoVideo());
        stmt.bindString(11, entity.getInfoAudio());
        stmt.bindString(12, entity.getOccurrence());
        stmt.bindString(13, entity.getOccurrenceInformer());
        stmt.bindString(14, entity.getDivision());
        stmt.bindString(15, entity.getDivisionInformer());
        stmt.bindString(16, entity.getDistrict());
        stmt.bindString(17, entity.getDistrictInformer());
        stmt.bindLong(18, entity.getCreatedAt().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Crime readEntity(Cursor cursor, int offset) {
        Crime entity = new Crime( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // crimPosition
            cursor.getString(offset + 2), // crimCategory
            cursor.getString(offset + 3), // crimeInfo
            cursor.getString(offset + 4), // informerName
            cursor.getString(offset + 5), // informerPhone
            cursor.getString(offset + 6), // informerAddress
            cursor.getString(offset + 7), // infoDocument
            cursor.getString(offset + 8), // infoPicture
            cursor.getString(offset + 9), // infoVideo
            cursor.getString(offset + 10), // infoAudio
            cursor.getString(offset + 11), // occurrence
            cursor.getString(offset + 12), // occurrenceInformer
            cursor.getString(offset + 13), // division
            cursor.getString(offset + 14), // divisionInformer
            cursor.getString(offset + 15), // district
            cursor.getString(offset + 16), // districtInformer
            new java.util.Date(cursor.getLong(offset + 17)) // createdAt
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Crime entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCrimPosition(cursor.getInt(offset + 1));
        entity.setCrimCategory(cursor.getString(offset + 2));
        entity.setCrimeInfo(cursor.getString(offset + 3));
        entity.setInformerName(cursor.getString(offset + 4));
        entity.setInformerPhone(cursor.getString(offset + 5));
        entity.setInformerAddress(cursor.getString(offset + 6));
        entity.setInfoDocument(cursor.getString(offset + 7));
        entity.setInfoPicture(cursor.getString(offset + 8));
        entity.setInfoVideo(cursor.getString(offset + 9));
        entity.setInfoAudio(cursor.getString(offset + 10));
        entity.setOccurrence(cursor.getString(offset + 11));
        entity.setOccurrenceInformer(cursor.getString(offset + 12));
        entity.setDivision(cursor.getString(offset + 13));
        entity.setDivisionInformer(cursor.getString(offset + 14));
        entity.setDistrict(cursor.getString(offset + 15));
        entity.setDistrictInformer(cursor.getString(offset + 16));
        entity.setCreatedAt(new java.util.Date(cursor.getLong(offset + 17)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Crime entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Crime entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
